Regreesion Using Decision Tree
--

In [76]:
import pandas as pd
import numpy as np
data = pd.read_csv('insurance.csv')
ori_data = data

In [3]:
data.shape

(1338, 7)

In [4]:
data.head()

age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [5]:
data.describe()

age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [13]:
#there are some column with categorical data in the given data set, We have to convert it into numerical data

data.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [16]:
numeric_data_col = ['age','bmi','children']
categorical_data_col = ['sex','smoker','region']

from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
data['sex'] = le.fit_transform(data['sex'].astype('str'))   ##Converted gender values to 0 and 1

data['sex'].unique()

array([0, 1], dtype=int64)

In [19]:
#Before Transform
#data['smoker'].unique()
#array(['yes', 'no'], dtype=object)

data['smoker'] = le.fit_transform(data['smoker'].astype('str'))

#After Transform
data['smoker'].unique()
#array([1, 0], dtype=int64)

array([1, 0], dtype=int64)

In [22]:
#Before Transform
#data['region'].unique()
#array(['southwest', 'southeast', 'northwest', 'northeast'], dtype=object)

data['region'] = le.fit_transform(data['region'].astype('str'))

data['region'].unique()

array([3, 2, 1, 0], dtype=int64)

In [ ]:
####Till Above, I have converted the categorical data into numeric

IMP Note:- After the conversion We have to apply onehotencoding on each transformed column.

In [23]:
data.head(10)

age  sex     bmi  children  smoker  region      charges
0   19    0  27.900         0       1       3  16884.92400
1   18    1  33.770         1       0       2   1725.55230
2   28    1  33.000         3       0       2   4449.46200
3   33    1  22.705         0       0       1  21984.47061
4   32    1  28.880         0       0       1   3866.85520
5   31    0  25.740         0       0       2   3756.62160
6   46    0  33.440         1       0       2   8240.58960
7   37    0  27.740         3       0       1   7281.50560
8   37    1  29.830         2       0       0   6406.41070
9   60    0  25.840         0       0       1  28923.13692

In [77]:
sex_on_hot_encoded = pd.get_dummies(data['sex'])
#sex_on_hot_encoded
#type(sex_on_hot_encoded)          pandas.core.frame.DataFrame

new_data = pd.concat([data[['age', 'bmi', 'children', 'smoker', 'region', 'charges']],sex_on_hot_encoded],axis=1)

#new_data.head(10)

new_data = pd.get_dummies(new_data)

data = new_data
new_data.head()

age     bmi  children      charges  female  male  smoker_no  smoker_yes  \
0   19  27.900         0  16884.92400       1     0          0           1   
1   18  33.770         1   1725.55230       0     1          1           0   
2   28  33.000         3   4449.46200       0     1          1           0   
3   33  22.705         0  21984.47061       0     1          1           0   
4   32  28.880         0   3866.85520       0     1          1           0   

   region_northeast  region_northwest  region_southeast  region_southwest  
0                 0                 0                 0                 1  
1                 0                 0                 1                 0  
2                 0                 0                 1                 0  
3                 0                 1                 0                 0  
4                 0                 1                 0                 0

In [69]:
####Import the Above Resut Image Here
#data = data = pd.get_dummies(data)
#data

In [62]:
#one_hot_encoded_smoker = le.fit_transform(data['smoker'].astype('str'))

#one_hot_encoded_smoker

array([1, 0, 0, ..., 0, 0, 1])

In [86]:
X = new_data.drop('charges', axis=1)
y = new_data['charges'] 

In [87]:
#Split the data
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size= 0.25, random_state = 0)

In [85]:
print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(1003, 11)
(335, 11)
(1003,)
(335,)


In [80]:
new_data.columns

Index(['age', 'bmi', 'children', 'charges', 'female', 'male', 'smoker_no',
       'smoker_yes', 'region_northeast', 'region_northwest',
       'region_southeast', 'region_southwest'],
      dtype='object')

In [78]:
#new_data2 = pd.concat([data[['age', 'bmi', 'children', 'region', 'charges', 0, 1]],one_hot_encoded_smoker],axis=1)

In [88]:
from sklearn.tree import DecisionTreeRegressor

dr = DecisionTreeRegressor()

#Train the model using fit function
dr.fit(X_train, y_train)

DecisionTreeRegressor(criterion='mse', max_depth=None, max_features=None,
           max_leaf_nodes=None, min_impurity_decrease=0.0,
           min_impurity_split=None, min_samples_leaf=1,
           min_samples_split=2, min_weight_fraction_leaf=0.0,
           presort=False, random_state=None, splitter='best')

In [89]:
y_pred = dr.predict(X_test)

In [91]:
compare_result = pd.DataFrame({'Actual_result': y_test, 'Pred_result': y_pred})

In [92]:
compare_result.head(10)

Actual_result  Pred_result
578      9724.53000  10085.84600
610      8547.69130   8233.09750
569     45702.02235  44202.65360
1034    12950.07120  13429.03540
198      9644.25250   9566.99090
981      4500.33925   7228.21565
31       2198.18985   2196.47320
1256    11436.73815  10560.49170
1219     7537.16390   7209.49180
1320     5425.02335   5693.43050

In [93]:
from sklearn import metrics

print("Absolute error", metrics.mean_absolute_error(y_pred, y_test))

Absolute error 2914.1577305343285


In [94]:
print("Absolute error", metrics.mean_absolute_error(y_test, y_pred))

Absolute error 2914.1577305343285


In [95]:
print("Mean squared error", metrics.mean_squared_error(y_test, y_pred))

Mean squared error 42253042.593765825


In [96]:
print("Root Mean Squeared Error", np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Root Mean Squeared Error 6500.234041460802


In [ ]:
Value of Root Mean squared Value is more than 50% of the Mean value.